[build]
  publish = "dist"
  command = "npm run build && npm run build --prefix portal && cp -r portal/dist dist/portal && cp sitemap.xml robots.txt dist/"

[[redirects]]
  from = "/portal/*"
  to = "/portal/index.html"
  status = 200
